on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akangular.azurecr.io
        username: ${{ secrets.acr_akangular_username }}
        password: ${{ secrets.acr_akangular_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t akangular.azurecr.io/akcluster:${{ github.sha }}
        docker push akangular.azurecr.io/akcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akcluster90e5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akcluster90e5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akcluster90e5
        container-registry-url: akangular.azurecr.io
        container-registry-username: ${{ secrets.acr_akangular_username }}
        container-registry-password: ${{ secrets.acr_akangular_password }}
        secret-name: akclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akcluster90e5
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          akangular.azurecr.io/akcluster:${{ github.sha }}
        imagepullsecrets: |
          akclusterdockerauth