on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akangular.azurecr.io
        username: ${{ secrets.acr_akangular_username }}
        password: ${{ secrets.acr_akangular_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t akangular.azurecr.io/kubernetesserver:${{ github.sha }}
        docker push akangular.azurecr.io/kubernetesserver:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernetesserver_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetesserver9e0e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetesserver9e0e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetesserver9e0e
        container-registry-url: akangular.azurecr.io
        container-registry-username: ${{ secrets.acr_akangular_username }}
        container-registry-password: ${{ secrets.acr_akangular_password }}
        secret-name: kubernetessedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernetesserver9e0e
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          akangular.azurecr.io/kubernetesserver:${{ github.sha }}
        imagepullsecrets: |
          kubernetessedockerauth